import { spawn, type ChildProcess } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

import type { EnvPaths } from "../lib/paths.ts"
import { shellQuote } from "../lib/shell.ts"
import * as log from "../lib/log.ts"

/**
 * The sandbox launcher.
 *
 * moat does not use Docker, podman or any container runtime. It builds the
 * isolation directly out of Linux primitives, because that is the only thing
 * that works with zero privileges on the target host:
 *
 *   unshare --user --map-root-user   -> we become uid 0 *inside* a user namespace,
 *                                       mapped to the calling user outside it
 *           --mount                  -> private mount namespace
 *           --pid --fork             -> private PID namespace (sandbox sees only itself)
 *           --uts --ipc              -> private hostname and IPC
 *           --kill-child             -> sandbox dies with the supervisor
 *
 * Inside that namespace the outer script:
 *   1. binds the persistent rootfs onto a scratch mount point,
 *   2. builds a mount table (proc, tmpfs /dev, devpts, /dev/shm, /tmp, /run),
 *   3. bind-mounts *device nodes only* from the host (see DEVICE_NODES note),
 *   4. chroots into it and execs the entry script.
 *
 * What is deliberately NOT here: no bind mount of the project, the home
 * directory, the SSH agent, the container socket, or any host environment
 * variable. Copy-in happens before boot (see sync/copyin.ts); copy-out happens
 * through git (see sync/copyout.ts).
 *
 * DEVICE_NODES note: `mknod` is refused inside an unprivileged user namespace
 * (verified: EPERM), so /dev/null and friends cannot be created from nothing.
 * Every rootless runtime resolves this the same way: bind the host's *device
 * nodes* read-only. These carry no host data and are the only host-originated
 * mount in the sandbox; `moat doctor` prints the full mount table so you can
 * check that claim yourself.
 */
const DEVICE_NODES = ["null", "zero", "full", "random", "urandom", "tty"] as const

export type SandboxSpawn = {
  rootfs: string
  mountpoint: string
  entry: string
  /** Absolute path inside the rootfs of a script to exec. */
  innerScript: string
}

export function newroot(p: EnvPaths): string {
  return p.mountpoint
}

/**
 * The outer script runs on the *host* filesystem, inside the fresh namespaces,
 * using the host's own `mount`/`chroot`. Keeping it in a file (rather than in
 * `sh -c`) removes an entire class of quoting bugs, and means the exact boot
 * sequence is auditable on disk after the fact.
 */
export function outerScript(p: EnvPaths): string {
  const N = shellQuote(newroot(p))
  const R = shellQuote(p.rootfs)
  const inner = shellQuote(`/.moat/${path.basename(p.entryScript)}`)
  const lines: string[] = []
  lines.push("#!/bin/sh")
  lines.push("# GENERATED BY moat, the exact sandbox boot sequence. No project data is mounted.")
  lines.push("set -eu")
  lines.push(`N=${N}`)
  lines.push(`R=${R}`)
  // Make the whole tree private first, so nothing we mount here can propagate
  // back into the host's mount namespace.
  lines.push(`mount --make-rprivate / 2>/dev/null || true`)
  lines.push(`mkdir -p "$N"`)
  lines.push(`mount --bind "$R" "$N"`)
  lines.push(`mount -t proc proc "$N/proc"`)
  lines.push(`mount -t tmpfs -o mode=755,nosuid tmpfs "$N/dev"`)
  lines.push(`mkdir -p "$N/dev/pts" "$N/dev/shm"`)
  for (const node of DEVICE_NODES) {
    lines.push(`if [ -e /dev/${node} ]; then : > "$N/dev/${node}"; mount --bind "/dev/${node}" "$N/dev/${node}" 2>/dev/null || true; fi`)
  }
  // devpts must not be given gid=5: gid 5 is not mapped in our single-id user
  // namespace and the mount fails with EINVAL. Verified behaviour.
  lines.push(`mount -t devpts -o newinstance,ptmxmode=0666,mode=620 devpts "$N/dev/pts" 2>/dev/null || true`)
  lines.push(`ln -sf pts/ptmx "$N/dev/ptmx"`)
  lines.push(`mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs "$N/dev/shm"`)
  lines.push(`mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs "$N/tmp"`)
  lines.push(`mount -t tmpfs -o mode=755,nosuid,nodev tmpfs "$N/run"`)
  // A copy, not a mount: the sandbox needs a resolver and has no host netns of its own.
  lines.push(`cp /etc/resolv.conf "$N/etc/resolv.conf" 2>/dev/null || true`)
  lines.push(`exec chroot "$N" /bin/sh ${inner}`)
  return `${lines.join("\n")}\n`
}

export function writeOuterScript(p: EnvPaths): string {
  const file = path.join(p.dir, "runtime", "boot.sh")
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, outerScript(p), { mode: 0o700 })
  return file
}

/** Write the script that executes *inside* the rootfs. It must never contain a secret. */
export function writeInnerScript(p: EnvPaths, body: string): string {
  const dir = path.join(p.rootfs, ".moat")
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(p.entryScript, body, { mode: 0o755 })
  return p.entryScript
}

export type SandboxEnv = Record<string, string | undefined>

/** The only environment variables that reach the sandbox. Nothing is forwarded implicitly. */
export function sandboxEnv(extra: SandboxEnv = {}): NodeJS.ProcessEnv {
  return {
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    HOME: "/root",
    LANG: "C.UTF-8",
    LC_ALL: "C.UTF-8",
    TERM: "dumb",
    MOAT_SANDBOX: "1",
    ...extra,
  } as NodeJS.ProcessEnv
}

export function unshareArgs(inner: string): string[] {
  return [
    "--user",
    "--map-root-user",
    "--mount",
    "--pid",
    "--fork",
    "--uts",
    "--ipc",
    "--kill-child",
    "sh",
    inner,
  ]
}

/** Run a script inside a *fresh, ephemeral* boot of the sandbox and wait for it. */
export async function runInSandbox(
  p: EnvPaths,
  innerBody: string,
  opts: { env?: SandboxEnv; onOutput?: (chunk: string) => void } = {},
): Promise<{ code: number; output: string }> {
  writeInnerScript(p, innerBody)
  const boot = writeOuterScript(p)
  return await new Promise((resolve, reject) => {
    const child = spawn("unshare", unshareArgs(boot), {
      env: sandboxEnv(opts.env),
      stdio: ["ignore", "pipe", "pipe"],
    })
    let output = ""
    const sink = (chunk: string) => {
      output += chunk
      opts.onOutput?.(chunk)
    }
    child.stdout.setEncoding("utf8")
    child.stderr.setEncoding("utf8")
    child.stdout.on("data", sink)
    child.stderr.on("data", sink)
    child.on("error", reject)
    child.on("close", (code) => resolve({ code: code ?? -1, output }))
  })
}

export type SandboxProcess = {
  child: ChildProcess
  pid: number
  logFile: string
}

/** Boot the sandbox as a long-running server, detached into its own process group. */
export function startSandbox(p: EnvPaths, innerBody: string, env: SandboxEnv): SandboxProcess {
  writeInnerScript(p, innerBody)
  const boot = writeOuterScript(p)
  fs.mkdirSync(p.logs, { recursive: true })
  const logFile = path.join(p.logs, "sandbox.log")
  const fd = fs.openSync(logFile, "a")
  const child = spawn("unshare", unshareArgs(boot), {
    env: sandboxEnv(env),
    stdio: ["ignore", fd, fd],
    detached: true,
  })
  child.unref()
  fs.closeSync(fd)
  if (!child.pid) throw new Error("failed to spawn sandbox: no pid")
  return { child, pid: child.pid, logFile }
}

/**
 * Stop a sandbox by killing its whole process group.
 *
 * The group is created by `detached: true`, so a single negative-pid signal
 * reaches unshare, the boot script and opencode together; `--kill-child` on
 * unshare then guarantees the PID-namespace init cannot outlive it.
 */
export async function stopSandbox(pid: number, opts: { timeoutMs?: number } = {}): Promise<boolean> {
  const timeoutMs = opts.timeoutMs ?? 5000
  const alive = (): boolean => {
    try {
      process.kill(pid, 0)
      return true
    } catch {
      return false
    }
  }
  if (!alive()) return true
  try {
    process.kill(-pid, "SIGTERM")
  } catch {
    try {
      process.kill(pid, "SIGTERM")
    } catch {
      /* already gone */
    }
  }
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    if (!alive()) return true
    await new Promise((r) => setTimeout(r, 100))
  }
  log.debug(`sandbox pid ${pid} had not exited after ${timeoutMs}ms; escalating to SIGKILL`)
  try {
    process.kill(-pid, "SIGKILL")
  } catch {
    try {
      process.kill(pid, "SIGKILL")
    } catch {
      /* already gone */
    }
  }
  await new Promise((r) => setTimeout(r, 200))
  return !alive()
}

export function isRunning(pid: number | null): boolean {
  if (!pid) return false
  try {
    process.kill(pid, 0)
    return true
  } catch {
    return false
  }
}
